apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: gastos
  labels:
    app: gastos
    component: database
spec:
  selector:
    app: gastos
    component: database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
