apiVersion: v1
kind: Secret
metadata:
  name: gastos-secrets
  namespace: gastos
type: Opaque
stringData:
  DB_USER: gastos_user
  DB_PASS: changeme
  DB_NAME: gastos
  JWT_SECRET: change-me-in-production
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
